//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int ID { get; set; }
        public Nullable<int> IDCustomer { get; set; }
        public string Name { get; set; }
        public string ContentFeedback { get; set; }
        public string Image { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Browser { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
